import React, { createContext, useState, useContext, useEffect } from 'react';

const LanguageContext = createContext();

const translations = {
  ru: {
    // Auth page
    currency_symbol: 'сум',
    authTitle: 'Контролируйте свои финансы легко и красиво',
    authSubtitle: 'Аналитика расходов и доходов Узбекистана, лимиты, интеграция с картами Uzcard/Humo и экспорт в CSV.',
    authMockTitle: 'Аналитика Баланса',
    authMockActive: 'Активен',
    authLoginTab: 'Вход в систему',
    authRegisterTab: 'Регистрация',
    authName: 'Ваше имя',
    authEmail: 'E-mail адрес',
    authEmailOrPhone: 'E-mail или телефон',
    authPhone: 'Номер телефона',
    authPassword: 'Пароль',
    authConfirmPassword: 'Подтвердите пароль',
    authShowPassword: '👁️',
    authForgotPassword: 'Забыли пароль?',
    authDemoHelp: 'Введите данные учетной записи для входа или создайте новую.',
    authSignUpBtn: 'Зарегистрироваться',
    authSignInBtn: 'Войти в личный кабинет',
    authErrName: 'Введите ваше имя',
    authErrEmail: 'Введите корректный E-mail',
    authErrPhone: 'Введите корректный номер телефона',
    authErrPassSafety: 'Пароль не удовлетворяет требованиям безопасности',
    authErrPassMismatch: 'Пароли не совпадают',
    authErrUserExists: 'Пользователь уже зарегистрирован',
    authErrInvalidCreds: 'Неверный логин или пароль',
    
    // Sidebar & BottomNav
    brandTitle: 'CASHFLOW UZ',
    brandSubtitle: 'Умный учёт',
    statusActive: 'Активен',
    newTransaction: 'Новая операция',
    tabDashboard: 'Дашборд',
    tabIncomes: 'Доходы',
    tabExpenses: 'Расходы',
    tabTransactions: 'Транзакции',
    tabSettings: 'Настройки',
    logoutConfirm: 'Вы действительно хотите выйти?',
    logoutBtn: 'Выйти',

    // Dashboard
    welcome: 'Привет',
    overviewText: 'Вот обзор ваших финансов на сегодня (Узбекистан).',
    totalBalance: 'Общий баланс',
    availableFunds: 'Все доступные средства на счетах',
    incomesLabel: 'Доходы',
    expensesLabel: 'Расходы',
    incomesTrend: '📈 Увеличились в этом месяце',
    expensesTrend: '📉 Под контролем',
    chartTitle: 'Динамика за 7 дней',
    chartSubtitle: 'Доходы и расходы по дням',
    monthlyLimit: 'Месячный лимит',
    monthlySpent: 'Потрачено в этом месяце:',
    limitExceeded: '⚠️ Лимит превышен! Рекомендуется сократить расходы.',
    limitRemaining: 'Осталось лимита:',
    limitNotSet: 'Лимит расходов не установлен',
    limitSetHelp: 'Укажите его в настройках, чтобы контролировать бюджет',
    topCategories: 'Топ категорий расходов',
    noExpenses: 'Нет зарегистрированных расходов',
    recentTransactions: 'Последние операции',
    recentSubtitle: 'История за последнее время',
    noTransactions: 'У вас пока нет транзакций',
    addFirstTrans: 'Добавьте банковскую карту и транзакции, чтобы начать отслеживание бюджета',
    deleteConfirm: 'Удалить эту транзакцию?',
    
    // Add Transaction Modal
    modalNewTrans: 'Новая транзакция',
    modalEditTrans: 'Редактировать операцию',
    modalExpense: '💸 Расход',
    modalIncome: '💰 Доход',
    modalAmount: 'Сумма',
    modalCategory: 'Категория',
    modalDate: 'Дата',
    modalDesc: 'Описание (необязательно)',
    modalBank: 'Карта / Банк',
    modalCancel: 'Отмена',
    modalSave: 'Сохранить',
    modalAdd: 'Добавить',
    modalErrAmount: 'Пожалуйста, введите корректную сумму',
    
    // Categories
    cat_food: '🍔 Продукты и кафе',
    cat_transport: '🚗 Транспорт',
    cat_housing: '🏠 Жилье и коммунальные',
    cat_entertainment: '🎬 Развлечения',
    cat_shopping: '🛍️ Покупки',
    cat_health: '🏥 Здоровье',
    cat_other_expense: '🔄 Другое (Расход)',
    cat_salary: '💼 Зарплата',
    cat_freelance: '💻 Фриланс / Бизнес',
    cat_investments: '📈 Инвестиции',
    cat_gifts: '🎁 Подарки',
    cat_other_income: '🔄 Другое (Доход)',

    // Banks
    bank_humo: '💳 Humo Карта',
    bank_uzcard: '💳 Uzcard Карта',
    bank_tbc: '🟢 TBC Bank Uzbekistan',
    bank_anor: '🔴 Anorbank',
    bank_kapital: '🔵 Kapitalbank',
    bank_cash: '💵 Наличные (Naqd)',
    
    // Incomes / Expenses Pages
    incTitle: 'Доходы 📈',
    incSubtitle: 'Управление доходными операциями и аналитика поступлений',
    expTitle: 'Расходы 📉',
    expSubtitle: 'Анализ и учет расходов, контроль за бюджетом по категориям',
    statTotal: 'Общая сумма',
    statAvg: 'Средний чек',
    statMax: 'Максимальная сумма',
    searchPlaceholder: 'Поиск по описанию...',
    allCategories: 'Все категории',
    historyLabel: 'История операций',
    noDataTitle: 'Операций не найдено',
    noDataSubtitle: 'Попробуйте изменить параметры поиска или фильтров',
    breakdownTitle: 'Распределение бюджета',
    breakdownSubtitle: 'Анализ долей по категориям',
    
    // Transactions History
    transTitle: 'Все транзакции 🔄',
    transSubtitle: 'Просмотр, фильтрация, редактирование и экспорт всей истории операций',
    exportBtn: '📤 Экспорт в CSV',
    labelType: 'Тип',
    labelSort: 'Сортировка',
    sortNew: 'Сначала новые (дата)',
    sortOld: 'Сначала старые (дата)',
    sortDesc: 'По убыванию суммы',
    sortAsc: 'По возрастанию суммы',
    thDate: 'Дата',
    thDesc: 'Описание / Категория / Банк',
    thType: 'Тип',
    thAmount: 'Сумма',
    thActions: 'Действия',
    noTransFilter: 'Нет транзакций, удовлетворяющих критериям фильтра',

    // Settings
    settingsTitle: 'Настройки профиля ⚙️',
    settingsSubtitle: 'Настройте имя, основную валюту Узбекистана и лимит',
    labelName: 'Ваше имя',
    labelCurrency: 'Основная валюта',
    labelLimit: 'Месячный лимит расходов (0 — без лимита)',
    saveChangesBtn: 'Сохранить изменения',
    savedSuccess: '✓ Настройки сохранены!',
    sysTitle: 'Системные операции',
    sysSubtitle: 'Управление демонстрационными данными и сброс системы',
    demoTitle: 'Демонстрационные данные',
    demoDesc: 'Загрузите готовый набор транзакций в сумах (so\'m), чтобы увидеть графики и лимиты в действии.',
    demoBtn: '🔄 Загрузить демо-данные UZS',
    resetTitle: 'Очистка и сброс',
    resetDesc: 'Сбросит все настройки до стандартных значений и удалит абсолютно все добавленные транзакции.',
    resetBtn: '🗑️ Сбросить всё',
    sessionTitle: 'Выход из системы',
    sessionDesc: 'Выйти из текущего аккаунта. Все ваши локальные транзакции сохранятся под вашим профилем.',
    sessionBtn: '🚪 Выйти из аккаунта',
    resetConfirm: 'Вы уверены, что хотите полностью сбросить данные? Это действие нельзя отменить.',
    resetAlert: 'Данные сброшены!',
    demoAlert: 'Демо-данные в узбекских сумах успешно загружены!',
    logoutSettingsConfirm: 'Вы действительно хотите выйти из аккаунта?',

    // NEW Uzbekistan Card & SMS & Admin panel translations
    cardManager: 'Мои банковские карты',
    cardAdd: 'Привязать карту',
    cardName: 'Название карты (напр., TBC Humo)',
    cardNumber: 'Номер карты (16 цифр)',
    cardBalance: 'Начальный баланс на карте',
    cardHumo: 'Humo Карта',
    cardUzcard: 'Uzcard Карта',
    cardVisa: 'Visa',
    cardMaster: 'Mastercard',
    smsParser: 'Автоматический импорт из СМС банка',
    smsPlaceholder: 'Вставьте текст СМС от банка. Например: \nChiqim: 45000 UZS. Korzinka. Karta: Humo *1234\nили\nKirim: 1200000 UZS. Oylik. Karta: Uzcard *8899',
    smsParseBtn: 'Распознать и записать операцию',
    smsSuccess: '✓ Операция успешно распознана и записана!',
    smsError: '❌ Не удалось распознать формат СМС. Введите вручную.',
    adminPanel: 'Панель Администратора',
    adminUsersList: 'Зарегистрированные пользователи',
    adminStatsUsers: 'Пользователей',
    adminStatsTrans: 'Всего операций',
    adminStatsAvg: 'Средний баланс',
    adminDetailTitle: 'Характеристики до ходов и уходов',
    adminDeleteConfirm: 'Вы действительно хотите полностью удалить этого пользователя со всей его историей?',
    adminNoUsers: 'В системе пока нет других пользователей.',
    adminRawStorage: 'Просмотр локальной базы данных (RAW JSON)',
    adminRawDesc: 'Здесь вы можете видеть, как ваши данные реально хранятся в LocalStorage компании.',
    cardNotFound: '❌ Карта не найдена'
  },
  uz: {
    // Auth page
    currency_symbol: "so'm",
    authTitle: 'Moliyangizni oson va chiroyli nazorat qiling',
    authSubtitle: 'O\'zbekiston xarajatlari va daromadlari tahlili, cheklovlar, Uzcard/Humo kartalari integratsiyasi va CSV eksport.',
    authMockTitle: 'Balans Tahlili',
    authMockActive: 'Faol',
    authLoginTab: 'Tizimga kirish',
    authRegisterTab: 'Ro\'yxatdan o\'tish',
    authName: 'Ismingiz',
    authEmail: 'E-mail manzilingiz',
    authEmailOrPhone: 'E-mail yoki telefon raqami',
    authPhone: 'Telefon raqamingiz',
    authPassword: 'Parol',
    authConfirmPassword: 'Parolni tasdiqlang',
    authShowPassword: '👁️',
    authForgotPassword: 'Parolni unutdingizmi?',
    authDemoHelp: 'Tizimga kirish uchun hisob ma\'lumotlarini kiriting yoki yangi hisob yarating.',
    authSignUpBtn: 'Ro\'yxatdan o\'tish',
    authSignInBtn: 'Shaxsiy kabinetga kirish',
    authErrName: 'Ismingizni kiriting',
    authErrEmail: 'To\'g\'ri E-mail kiriting',
    authErrPhone: 'To\'g\'ri telefon raqami kiriting',
    authErrPassSafety: 'Parol xavfsizlik talablariga javob bermaydi',
    authErrPassMismatch: 'Parollar mos kelmadi',
    authErrUserExists: 'Foydalanuvchi allaqachon ro\'yxatdan o\'tgan',
    authErrInvalidCreds: 'Noto\'g\'ri login yoki parol',

    // Sidebar & BottomNav
    brandTitle: 'CASHFLOW UZ',
    brandSubtitle: 'Aqlli hisob',
    statusActive: 'Faol',
    newTransaction: 'Yangi operatsiya',
    tabDashboard: 'Boshqaruv',
    tabIncomes: 'Daromadlar',
    tabExpenses: 'Xarajatlar',
    tabTransactions: 'Tranzaksiyalar',
    tabSettings: 'Sozlamalar',
    logoutConfirm: 'Haqiqatan ham tizimdan chiqmoqchimisiz?',
    logoutBtn: 'Chiqish',

    // Dashboard
    welcome: 'Salom',
    overviewText: 'Bugungi moliyaviy holatingiz tahlili (O\'zbekiston).',
    totalBalance: 'Umumiy balans',
    availableFunds: 'Hisoblardagi barcha mavjud mablag\'lar',
    incomesLabel: 'Daromadlar',
    expensesLabel: 'Xarajatlar',
    incomesTrend: '📈 Shu oyda ko\'paydi',
    expensesTrend: '📉 Nazorat ostida',
    chartTitle: '7 kunlik dinamika',
    chartSubtitle: 'Kunlik daromad va xarajatlar',
    monthlyLimit: 'Oylik limit',
    monthlySpent: 'Shu oyda sarflandi:',
    limitExceeded: '⚠️ Limitdan oshib ketdi! Xarajatlarni kamaytirish tavsiya etiladi.',
    limitRemaining: 'Limit qoldiqi:',
    limitNotSet: 'Xarajat limiti o\'rnatilmagan',
    limitSetHelp: 'Byudjetni nazorat qilish uchun uni sozlamalarda ko\'rsating',
    topCategories: 'Eng ko\'p sarflangan kategoriyalar',
    noExpenses: 'Xarajatlar ro\'yxatga olinmagan',
    recentTransactions: 'Oxirgi operatsiyalar',
    recentSubtitle: 'Yaqindagi operatsiyalar tarixi',
    noTransactions: 'Sizda hali tranzaksiyalar yo\'q',
    addFirstTrans: 'Byudjetni nazorat qilishni boshlash uchun bank kartangizni va tranzaksiyalarni qo\'shing',
    deleteConfirm: 'Ushbu tranzaksiyani o\'chirib tashlaysizmi?',

    // Add Transaction Modal
    modalNewTrans: 'Yangi tranzaksiya',
    modalEditTrans: 'Operatsiyani tahrirlash',
    modalExpense: '💸 Xarajat',
    modalIncome: '💰 Daromad',
    modalAmount: 'Summa',
    modalCategory: 'Kategoriya',
    modalDate: 'Sana',
    modalDesc: 'Izoh (ixtiyoriy)',
    modalBank: 'Karta / Bank',
    modalCancel: 'Bekor qilish',
    modalSave: 'Saqlash',
    modalAdd: 'Qo\'shish',
    modalErrAmount: 'Iltimos, to\'g\'ri summani kiriting',

    // Categories
    cat_food: '🍔 Oziq-ovqat va kafe',
    cat_transport: '🚗 Transport',
    cat_housing: '🏠 Uy-joy va kommunal',
    cat_entertainment: '🎬 Ko\'ngilochar',
    cat_shopping: '🛍️ Xaridlar',
    cat_health: '🏥 Sog\'liqni saqlash',
    cat_other_expense: '🔄 Boshqa (Xarajat)',
    cat_salary: '💼 Oylik maosh',
    cat_freelance: '💻 Freelans va Biznes',
    cat_investments: '📈 Investitsiyalar',
    cat_gifts: '🎁 Sovg\'alar',
    cat_other_income: '🔄 Boshqa (Daromad)',

    // Banks
    bank_humo: '💳 Humo kartasi',
    bank_uzcard: '💳 Uzcard kartasi',
    bank_tbc: '🟢 TBC Bank Uzbekistan',
    bank_anor: '🔴 Anorbank',
    bank_kapital: '🔵 Kapitalbank',
    bank_cash: '💵 Naqd pul (Naqd)',

    // Incomes / Expenses Pages
    incTitle: 'Daromadlar 📈',
    incSubtitle: 'Daromad operatsiyalarini boshqarish va tushumlar tahlili',
    expTitle: 'Xarajatlar 📉',
    expSubtitle: 'Xarajatlarni tahlil qilish va kategoriyalar bo\'yicha byudjet nazorati',
    statTotal: 'Umumiy summa',
    statAvg: 'O\'rtacha chek',
    statMax: 'Maksimal summa',
    searchPlaceholder: 'Izoh bo\'yicha qidiruv...',
    allCategories: 'Barcha kategoriyalar',
    historyLabel: 'Operatsiyalar tarixi',
    noDataTitle: 'Operatsiyalar topilmadi',
    noDataSubtitle: 'Qidiruv yoki filtr parametrlarini o\'zgartirib ko\'ring',
    breakdownTitle: 'Byudjet taqsimoti',
    breakdownSubtitle: 'Kategoriyalar bo\'yicha ulush tahlili',

    // Transactions History
    transTitle: 'Barcha tranzaksiyalar 🔄',
    transSubtitle: 'Barcha operatsiyalar tarixini ko\'rish, filtrlash, tahrirlash va eksport qilish',
    exportBtn: '📤 CSV eksport',
    labelType: 'Turi',
    labelSort: 'Saralash',
    sortNew: 'Avval yangilari (sana)',
    sortOld: 'Avval eskisi (sana)',
    sortDesc: 'Summa kamayishi bo\'yicha',
    sortAsc: 'Summa o\'sishi bo\'yicha',
    thDate: 'Sana',
    thDesc: 'Izoh / Kategoriya / Bank',
    thType: 'Turi',
    thAmount: 'Summa',
    thActions: 'Harakatlar',
    noTransFilter: 'Filtr mezonlariga mos keladigan tranzaksiyalar topilmadi',

    // Settings
    settingsTitle: 'Profil sozlamalari ⚙️',
    settingsSubtitle: 'Ismingiz, O\'zbekiston asosiy valyutasi va limitni sozlang',
    labelName: 'Ismingiz',
    labelCurrency: 'Asosiy valyuta',
    labelLimit: 'Oylik xarajat limiti (0 — limitsiz)',
    saveChangesBtn: 'O\'zgarishlarni saqlash',
    savedSuccess: '✓ Sozlamalar saqlandi!',
    sysTitle: 'Tizim operatsiyalari',
    sysSubtitle: 'Namoyish ma\'lumotlarini boshqarish va tizimni tiklash',
    demoTitle: 'Namoyish ma\'lumotlari',
    demoDesc: 'Grafik va limitlarni sinab ko\'rish uchun so\'m (so\'m) valyutasidagi tayyor tranzaksiyalar to\'plamini yuklang.',
    demoBtn: '🔄 UZS demo ma\'lumotlarni yuklash',
    resetTitle: 'Tozalash va tiklash',
    resetDesc: 'Barcha sozlamalarni standart qiymatlarga qaytaradi va barcha tranzaksiyalarni o\'chirib tashlaydi.',
    resetBtn: '🗑️ Hammasini o\'chirish',
    sessionTitle: 'Tizimdan chiqish',
    sessionDesc: 'Joriy hisobdan chiqish. Barcha tranzaksiyalaringiz profilingizda saqlanib qoladi.',
    sessionBtn: '🚪 Tizimdan chiqish',
    resetConfirm: 'Haqiqatan ham ma\'lumotlarni to\'liq o\'chirib tashlamoqchimisiz? Bu amalni bekor qilib bo\'lmaydi.',
    resetAlert: 'Ma\'lumotlar o\'chirildi!',
    demoAlert: 'O\'zbekiston so\'midagi demo ma\'lumotlar muvaffaqiyatli yuklandi!',
    logoutSettingsConfirm: 'Haqiqatan ham hisobdan chiqmoqchimisiz?',

    // NEW Uzbekistan Card & SMS & Admin panel translations
    cardManager: 'Mening bank kartalarim',
    cardAdd: 'Kartani ulash',
    cardName: 'Karta nomi (masalan, TBC Humo)',
    cardNumber: 'Karta raqami (16 ta raqam)',
    cardBalance: 'Kartadagi boshlang\'ich balans',
    cardHumo: 'Humo kartasi',
    cardUzcard: 'Uzcard kartasi',
    cardVisa: 'Visa',
    cardMaster: 'Mastercard',
    smsParser: 'Bank SMS xabarlaridan avtomatik import qilish',
    smsPlaceholder: 'Bank SMS xabarini kiriting. Masalan: \nChiqim: 45000 UZS. Korzinka. Karta: Humo *1234\nyoki\nKirim: 1200000 UZS. Oylik. Karta: Uzcard *8899',
    smsParseBtn: 'Xabarni aniqlash va yozib olish',
    smsSuccess: '✓ Operatsiya muvaffaqiyatli aniqlandi va saqlandi!',
    smsError: '❌ SMS formatini aniqlab bo\'lmadi. Qo\'lda kiriting.',
    adminPanel: 'Administrator paneli',
    adminUsersList: 'Ro\'yxatdan o\'tgan foydalanuvchilar',
    adminStatsUsers: 'Foydalanuvchilar',
    adminStatsTrans: 'Jami operatsiyalar',
    adminStatsAvg: 'O\'rtacha balans',
    adminDetailTitle: 'Kirim va chiqim xarakteristikalari',
    adminDeleteConfirm: 'Haqiqatan ham ushbu foydalanuvchini va uning barcha tarixini o\'chirib tashlamoqchimisiz?',
    adminNoUsers: 'Tizimda boshqa foydalanuvchilar mavjud emas.',
    adminRawStorage: 'Lokal ma\'lumotlar bazasini ko\'rish (RAW JSON)',
    adminRawDesc: 'Bu yerda siz ma\'lumotlaringiz LocalStorage-da qanday saqlanishini ko\'rishingiz mumkin.',
    cardNotFound: '❌ Karta topilmadi'
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('cashflow_lang') || 'ru';
  });

  useEffect(() => {
    localStorage.setItem('cashflow_lang', language);
    document.documentElement.lang = language;
  }, [language]);

  const t = (key) => {
    if (!translations[language]) return key;
    return translations[language][key] || translations['ru'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useTranslation = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useTranslation must be used within a LanguageProvider');
  }
  return context;
};
